

{
    "name" : 'Hospital Management',
    "version" : '11.0.1.0.0',
    "category" : 'Extra Tools',
    "summary" : 'Module for mapping the Hospital',
    "sequence" : '1',
    'depends': ['base','mail','sale','sale_stock','board','kanban_draggable','website_sale','purchase','purchase_requisition','sales_team'],
    "data": [
        'security/ir.model.access.csv',
        'security/security.xml',
        'wizards/create_appointment.xml',
        # 'data/mail_template.xml',
        'data/sequence.xml',
        'data/data.xml',
        'views/patient.xml',
        'views/lab.xml',
        'views/appointment.xml',
        'views/doctor.xml',
        'views/template.xml',
        'views/dashboard.xml',
        'views/settings.xml',
        'views/sales_settings_inherit.xml',
        'views/parameter_tree.xml',
        'views/sale_quotations.xml',
        'views/purchase_inherit.xml',
        'views/job_order.xml',
        'views/Rfq.xml',
        'views/ex_4.xml',
        'views/sale_order.xml',
        'views/server_action.xml',
        'views/website_form.xml',
        'views/partner_view.xml',
        'reports/report.xml',
        'reports/patient_card.xml',
        'reports/sale_report_inherit.xml',
        'reports/appointment.xml',
        'reports/invoice_card.xml',
    ],
    "installable" : True,
    "application" : True,
    "auto_install" : False
}